from fastapi import FastAPI, File, HTTPException, UploadFile

from app.config.settings import MODEL_DIR
from app.models.schemas import HealthResponse, PredictionResponse
from app.services.cnn_inference import load_model, predict_from_bytes
from app.services.health_service import get_health_status
from app.services.model_checkpoint import model_exists


app = FastAPI(
    title="GALLIVIS API",
    description=(
        "Intelligent Multimodal Clinical Decision Support System "
        "for Pre-operative Gallstone Classification"
    ),
    version="0.1.0",
)


CHECKPOINT_PATH = MODEL_DIR / "gallivis_cnn.pt"

DISCLAIMER = (
    "This result is generated by an AI model for clinical decision "
    "support only. It is not a medical diagnosis and does not "
    "guarantee the true gallstone composition. The final clinical "
    "decision must be made by a qualified doctor."
)

_model = None
_device = None


def _get_model():
    global _model, _device

    if _model is None:
        if not model_exists(CHECKPOINT_PATH):
            raise HTTPException(
                status_code=503,
                detail=(
                    "No trained GALLIVIS model checkpoint is available yet. "
                    "Training requires verified Cholesterol/Pigment/Mixed "
                    "composition labels, which the current dataset does "
                    "not have."
                ),
            )

        _model, _device = load_model(CHECKPOINT_PATH)

    return _model, _device


@app.get("/", tags=["General"])
def root():
    return {
        "project": "GALLIVIS",
        "message": "GALLIVIS API is running",
    }


@app.get("/health", response_model=HealthResponse, tags=["Health"])
def health_check():
    return get_health_status()


@app.post(
    "/predict/ultrasound",
    response_model=PredictionResponse,
    tags=["Prediction"],
)
async def predict_ultrasound(file: UploadFile = File(...)):

    if file.content_type not in ("image/jpeg", "image/png"):
        raise HTTPException(
            status_code=400,
            detail="Only JPEG or PNG images are supported.",
        )

    model, device = _get_model()

    image_bytes = await file.read()

    result = predict_from_bytes(model, image_bytes, device)

    return PredictionResponse(
        prediction=result["prediction"],
        confidence=result["confidence"],
        probabilities=result["probabilities"],
        disclaimer=DISCLAIMER,
    )